### PR TITLE
Use Naughty or Nice

### PR DESCRIPTION
**Pull request by benbalter**
This pull request moves the Gem to use Naughty or Nice, the underlying library that powers Swot (and GMan among others). It allows us to remove some of the domain validation, and have a common interface between classifier gems.

I tried to keep my commits as atomic as possible, and glad to submit them as multiple PRs if you'd prefer, but in short:
- Added a `script/` dir with bootstrap, cibuild, etc.
- Semantically versioned gem dependencies
- Moved the Gem to use Naughty or Nice (and refactored Record a bit to simplify things)
- HTML decoded firm names to get tests to pass
- Significantly expanded the test coverage 
- Added a Travis config file

There's a lot of noise in the diff, but the key files are https://github.com/benbalter/fortune-finder/blob/naughty_or_nice/lib/fortune-finder.rb and https://github.com/benbalter/fortune-finder/blob/naughty_or_nice/lib/fortune-finder/record.rb. 

To note the API should remain the same, meaning this would be a non-breaking change for existing use cases.

/cc @leereilly, @bkeepers

### CODE REVIEW

**Comment by bkeepers** [comment]
:metal:

**Comment by leereilly** [comment]
Thanks, @benbalter! Beers on me next time you're in town :beers:

**Comment by benbalter** [comment]
@leereilly just following your footsteps a few years later. :smile:

Tests pass for me locally (and I added a file if you want to enable travis), but if you're able to release a new version, we've got a use case internally in mind.

**Comment by leereilly** [comment]
:boom: enabled Travis, and cut a [new release](https://rubygems.org/gems/fortune-finder/versions/0.1.3). 

Thanks again, @benbalter! :bow:

**Pull request merged**
